Feature: Use of Hooks

Background: Verify backgound

# Background is used to define series of steps that are common to all the scenarios in the feature. the steps mentioned in the backgound
# are run before every scenario mentioned in the feature is run.

Given browser is opened

Then URL is launched

Scenario: Verify cheese

Then search for Cheese


Scenario: Verify searching for Gmail 


Then search for Gmail



